name: "Questions & Support"
description: "General questions and support for the modpack."
labels: ["question", "support"]
body:
  - type: markdown
    attributes:
      value: "### Need help? Ask your questions here."

  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "Describe what you need help with."
