blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://discord.gg/2sEahV9TXK
    about: General questions and support will be provided minecraft or Modpack related On Offical mptamilan's Discord!
