name: "Mod Request"
description: "Suggest a mod to be added, replaced, or removed."
labels: ["mod request"]
body:
  - type: markdown
    attributes:
      value: "### Please provide the details of the mod you want to add, replace, or remove."

  - type: input
    id: mod_name
    attributes:
      label: "Mod Name"
      description: "Enter the exact name of the mod."

  - type: textarea
    id: reason
    attributes:
      label: "Reason for the Request"
      description: "Explain why this mod should be added, replaced, or removed."
      placeholder: "e.g., This mod adds better performance features..."

  - type: input
    id: mod_link
    attributes:
      label: "Mod Link (CurseForge/GitHub)"
      description: "Provide a direct link to the mod."
