name: "Other Issue"
description: "Have a different issue? Use this template."
labels: ["other"]
body:
  - type: markdown
    attributes:
      value: "### Describe your issue."

  - type: textarea
    id: other_description
    attributes:
      label: "Describe the issue"
      description: "Provide as much detail as possible."
